apiVersion: v1
kind: Secret
metadata:
  name: dbsecrets
  namespace: {{ .Values.namespace }}
stringData:
  db.connection.rootpassword: {{ .Values.connection.rootPassword }}
  db.connection.user: {{ .Values.connection.user }}
  db.connection.password: {{ .Values.connection.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: defaultuser-secrets
  namespace: {{ .Values.namespace }}
stringData:
  defaultuser.username: {{ .Values.defaultUser.username }}
  defaultuser.password: {{ .Values.defaultUser.password }}
