kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbstorage-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

