apiVersion: v1
kind: Service
metadata:
  name: authdbservice
  namespace: {{ .Values.namespace }}
  labels:
    app: myportail
    service: authdbservice
spec:
  type: NodePort
  ports:
    - port: 3306
      name: mariadb
      targetPort: 3306
      nodePort: 30100
  selector:
    app: myportail
    service: authdb
