apiVersion: v1
kind: Service
metadata:
  name: authdbproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 3306
      name: mariadb
      targetPort: 3306
      nodePort: 30000
  selector:
    app: myportail
    service: authdb
