apiVersion: v1
kind: Service
metadata:
  name: authproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 8001
      name: web
      targetPort: 8001
  selector:
    app: myportail
    service: auth
