apiVersion: v1
kind: Service
metadata:
  name: authdbservice
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  selector:
    app: myportail
    service: authdb
