apiVersion: v1
kind: PersistentVolume
metadata:
  name: authdbstorage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/authdbstorage/

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdbstorage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
