kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authdbstorage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage

