apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportail-authdb
spec:
  selector:
    matchLabels:
      app: myportail
  template:
    metadata:
      labels:
        app: myportail
        service: authdb
    spec:
      volumes:
        - name: authdbstorage
          persistentVolumeClaim:
            claimName: authdbstorage-claim      
      containers:
        - name: authdb
          image: bitnami/mongodb:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: "/bitnami"
              name: authdbstorage
          env:
            - name: MONGODB_USERNAME
              value: authService
            - name: MONGODB_PASSWORD
              value: igQFUwjZZyxgken7gcKg*gTu
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: password123
            - name: MONGODB_ROOT_PASSWORD
              value: password123
            - name: MONGODB_DATABASE
              value: authdb
      initContainers:
        - name: authdb-perm-fix
          image: busybox
          command: ["/bin/chmod","-R","777", "/data"]
          volumeMounts:
            - name: authdbstorage
              mountPath: /data
