     
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myportail-auth
spec:
  selector:
    matchLabels:
      app: myportail
  template:
    metadata:
      labels:
        app: myportail
        service: auth
    spec:
      containers:
        - name: auth
          image: cobreti/myportail-auth-service:latest
          workingDir: /authService
          command: ["dotnet", "authService.dll"]
          ports:
            - containerPort: 8001
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
