     
apiVersion: v1
kind: Pod
metadata:
  name: myportail
  labels:
    app: web
spec:
  containers:
    - name: authdb
      image: bitnami/mongodb:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGODB_USERNAME
          value: authService
        - name: MONGODB_PASSWORD
          value: igQFUwjZZyxgken7gcKg*gTu
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password123
        - name: MONGODB_ROOT_PASSWORD
          value: password123
        - name: MONGODB_DATABASE
          value: authdb
