apiVersion: v1
kind: Service
metadata:
  name: authdbproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  selector:
    app: myportail
    service: authdb

---

apiVersion: v1
kind: Service
metadata:
  name: authproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 8001
      name: web
      targetPort: 8001
  selector:
    app: myportail
    service: auth
