apiVersion: v1
kind: Service
metadata:
  name: authdbproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  selector:
    app: myportail
    service: authdb

---

apiVersion: v1
kind: Service
metadata:
  name: authproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 8001
      name: web
      targetPort: 8001
  selector:
    app: myportail
    service: auth

---

apiVersion: v1
kind: Service
metadata:
  name: portailproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 8002
      name: web
      targetPort: 8002
  selector:
    app: myportail
    service: portail

---

apiVersion: v1
kind: Service
metadata:
  name: appgatewayproxy
  labels:
    app: myportail
spec:
  type: NodePort
  ports:
    - port: 8000
      name: appgateway
      targetPort: 8000
  selector:
    app: myportail
    service: appgateway
